name: 2.2 IPA Maker

on:
  workflow_dispatch:
    inputs:
      name:
        description: "GDPS Name"
        required: true
      url:
        description: "GDPS URL (33 CHARACTERS)"
        required: true
      bundle:
        description: "BUNDLE ID (23 CHARACTERS)"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        wget -L https://files.141412.xyz/r/base.ipa -O base.ipa
        npm install
        echo name=${{ inputs.name }} > .env
        echo bundle=${{ inputs.bundle }} >> .env
        echo url=${{ inputs.url }} >> .env
        node index.js
        
        # Check if the output file exists before moving it
        if [ -f "${{ inputs.name }}.ipa" ]; then
          mv ${{ inputs.name }}.ipa output.ipa
        else
          echo "Error: IPA file not found!"
          exit 1
        fi

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: "IPA Output" # optional, default is artifact
        path: "./output.ipa" # Use the full path to ensure it's found
        if-no-files-found: warn
